### ISSUE TITLE
Superfluous = signs

### ISSUE THREAD

**Issue by nylira** [psynix/rails3_haml_scaffold_generator#1]
Fantastic generator in almost every account. I'm just experiencing a small problem where Haml tags are being followed with '=' even though the content of that tag is plain text.

```
%p
  %strong= Year:
  = @car.year
```

&uarr; is being generated, instead of the proper &darr;

```
%p
  %strong Year:
   = @car.year
```

**Comment by psynix** [comment]
Thanks for report.

Just pushed a fix so you should be good-to-go.
